sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: "6"
branches:
  only:
    - master
notifications:
  email: true
script:
  - npm run validate
after_success:
  - npm run release
